import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from '@/components/Navbar';
import { AuthContextProvider } from '@/context/authcontext';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Navbar isLoggedIn={false} username={''} />
      <Head>
        <title>Acacia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  
    </>
  )
}
